title: Jekyll ZySo Theme- TODO (override title in project-specific _config.yml)

author:
  name: Kevin Moore
  email: zyronn.sorrow@gmail.com

description: >-
  This is the base theme for all websites/documentation for ZyronnSorrow's projects. TODO (override this description)

# Build Settings
theme: jekyll-theme-zyso

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections_dir: collections
collections:
  authors:
    output: true
    permalink: /:collection/:name
  posts:
    permalink: /blog/:categories/:title

# Layout & Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      header_enabled: true
      page_header: "TODO: Update page_header value in this page's front matter"
      footer_enabled: true
      styles_path: /assets/css/styles.css
      feed_enabled: true
      seo_enabled: true

# Other Settings - can be overriden in project-specific _config.yml
timezone: America/Denver
strict_front_matter: true

# Includes
include:
  - _pages
